#!/usr/bin/env python

__author__ = 'bharathipriyaa'
from myHashMap import MyHashMap
def test_map():
    myobject=MyHashMap()
    print "Hashmap.add(abc,1)"
    myobject.put("abc",1)
    print "Hashmap.get(abc)"
    print myobject.get("abc")
    print "Hashmap.add(abc,2)"
    myobject.put("abc",2)
    print "Hashmap.add(def,1)"
    myobject.put("def",1)
    print "Hashmap.get(def)"
    print myobject.get("def")
    print "Hashmap.get(abc)"
    print myobject.get("abc")

test_map()